library(rpart)
library(rpart.plot)
myData <- read.table("Test_Classif_dpt.txt", header = T)
summary(myData)
plot(myData$X1, myData$X2, col = myData$Y)
tree <- rpart(Y ~ ., myData)
prp(tree, extra = 1)
tree <- rpart(Y ~ ., myData, control = rpart.control(minsplit = 5, cp = 0))
prp(tree, extra = 1)

myData2 <- read.table("Test_Classif_Correl.txt", header = T)
myData2$Y <- as.character(myData2$Y)
plot(myData2$X1, myData2$X2, col = myData2$Y)
tree <- rpart(Y ~ ., myData2)
prp(tree, extra = 1)
tree <- rpart(Y ~ ., myData2, control = rpart.control(minsplit = 5, cp = 0))
prp(tree, extra = 1)
plotcp(tree)